# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 8000, host: {{ cookiecutter.vagrant_port }}

  config.vm.network "public_network"

  config.vm.synced_folder ".", "/app"

  config.vm.boot_timeout = 600

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.hostname = "{{ cookiecutter.project_slug }}-dev"

  config.vm.provision "shell", path: "provision/install.sh"
  config.vm.provision "shell", path: "provision/setup.sh"

end
