# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import todo.users.models.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(error_messages={'unique': 'This email address is already in use.'}, max_length=254, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=todo.users.models.utils.set_picture_filename, verbose_name='picture')),
                ('is_admin', models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.', verbose_name='admin status')),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether the user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='admin status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.', verbose_name='staff status')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Identifies the exact datetime when the user was first created', verbose_name='creation date')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Identifies the exact datetime when the user data was last modified', verbose_name='last modification date')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
